### ISSUE TITLE
Push message show package name (com.marshallofsound.gpmdp.core) when you like something

### ISSUE THREAD

**Issue by berryelectronics** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1654]
Not sure if this is a wont fix or if i've missed something in the issues:
![screenshot 17](https://cloud.githubusercontent.com/assets/12616124/18639180/2145bdaa-7e93-11e6-93ee-450df4a888fa.png)

Running on Windows 10

**Comment by jostrander** [comment]
This was an issue a while back, pretty sure it was resolved, is this while using the latest build?

**Comment by MarshallOfSound** [comment]
> This was an issue a while back, pretty sure it was resolved, is this while using the latest build?

It was indeed fixed, this means you are running an old version of the player, possibly due to a bug in `auto-launch` that was fixed a while back.

**Comment by berryelectronics** [comment]
didnt had the chance to build v4 by myself for windows (because dont manage that), so still runnnig 3.6
![2016-09-19_18-30-55](https://cloud.githubusercontent.com/assets/12616124/18640177/51e9aada-7e97-11e6-876d-5786382afa78.png)

in my autostart only the updater is listed.
I'll maybe try to do a fresh install later on

**Comment by MarshallOfSound** [comment]
@berryelectronics Can you try just clean restarted the application.  I.e. Quit and then re-open

**Comment by berryelectronics** [comment]
Did it, didnt changed a whole lot. still showing the same version in the about tab

**Comment by MarshallOfSound** [comment]
@berryelectronics You've run a development build before and sometimes windows get confused so I wouldn't be suprised if a computer restart or something made windows fix itself.  All I know is this occurs when windows can't find a `.exe` to associate with an `appUserModelID`.

Maybe you deleted all shortcuts to the application from the start menu / desktop?

**Comment by berryelectronics** [comment]
Hmm...didnt ran any build for a while on my main workstation (because well, cant set node up again in windows) and only in a VM, so only used the official builds. nah, started it through the shortcut on the desktop.

But gonna try a system restart (and prob. a reinstall) when a download is finished. will report back, but thanks for the help 👍
