### ISSUE TITLE
High CPU Usage with 3.6.0.0

### ISSUE THREAD

**Issue by Evaneaston** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1697]
I'm running GPMDP 3.6.0.0 on Win 10.  I've noticed since yesterday significant machine lag when the player is running, regardless of whether it is visible or closed to the tray.    It's high enough that it's causing my entire system to be sluggish.

The process consistently at the top of the CPU usage list is `Windows Audio Device Graph Isolation` (aka `AUDIODG.EXE`).  Interestingly, this process''s memory foot print grows and grows upward only. This morning, on my work machine, it was using over 3GB of memory.

There is also a significant amount of HTTPS network traffic to the host `yk-in-f104.1e100.net` resulting in significant `Service Host: Local Service (Network Restricted)` process CPU usage.

When completely close GPMDP and run the music player in Chrome, I don't have excessive CPU usage.  There is still traffic to `yk-in-f104.1e100.net` but a lot less.

It's as if the app is repeatedly setting up playback session over and over and leaking something inside `audiodg.exe`.

I've got a ProcMon log of events that I can share if it would help.

<img src="https://lh3.googleusercontent.com/hvjH0BLUlNZqBiexzZS6sAHfFp7JFSNrBfuN3DQ7DwZuy72v7Wwc9I0vtXMJDFAyRq-__XFUR4ZSvYt1fEiDwzDstgLnNKaIxwScRC_sva6Kw3QBs-Fmypdq1J0RWfisdmA3vw6q3yMjgJ2LHb_xKOwx6MmbP5VJwZJr9rvnf72OG77GZPgpHIMoPzHMFQmvUnqIeycCOSRkoi84uO_WBX7hwNwROaO4yOIoaqgVwoiBm29LCryPHgdlKrzGAB6sRM8FlK2emNH-oiXEvq1I488gzZ_3oPJLlTLy3p0xYaPrTVnPfVd0NxdgKBtBxUBBH2XwHIwTxd7yZ7QimTRFuyCpyGW-qP0svXLGTrzc8-BLchTVBF4hhRceOogoTq0mQc0HhZCPoYNqnJkcNJSe5dy05Y-9N2zvqBZaydQbtsNNxPIVNhCnzaYa3tCyUdrAsVDdx4sUVRnmNKyuj3X41F3das93LUWg2a4iY9nFWSE3X5i1EgH7v-wc-DF7rFTWe2FI-LoRI5C0GoUuUqb8IfFbg8NKzzuDOHtaByzgxkmG1O56I9BNSls7T31qAq5yQc7gcOQbp8YNyHfKpTQu3uVBv2g0C4wRkxn9dJ_AM6AN7yDPBg=w777-h571-no"/>

**Comment by WillPresley** [comment]
I legitimately thought this was an isolated issue that I was having, but I will +1 as having the exact same issues on Windows 10. I've also run LatencyMon (6.5 includes Win10 support) and it is showing a decent number of hard pagefaults from the GPMDP process as well, probably due to the causes mentioned by @Evaneaston. I can try to generate some logs/data as well, but the issue is very hit or miss, I will try to pin down some steps to reproduce if I can.

**Comment by MarshallOfSound** [comment]
I actually stumbled across this yesterday, we had an infinite asynchronous loop when setting the audio output device in certain situations.  So we would set the output device and then a few milliseconds set it to the same device.  Forever 😢 

This has been fixed in the `typescript` branch

**Comment by Evaneaston** [comment]
Even after the fix, I'm still getting ballooning memory usage from audiodg.exe and my realtek driver that stops when GPMDP is fully shutdown.

**Comment by Avangel27** [comment]
I have the same issue. I downloaded GPMDP yesterday and since than I have high usage of CPU and RAM. RAM is around 3.6 gb. If i stop the process GPMDP doesn't work but other applications do.
