### ISSUE TITLE
3.6.0 Audio Device Selection Issue

### ISSUE THREAD

**Issue by Dokupe** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1770]
**OS:**
Win7 SP1 64bit

**Issue Descriptions:**
Audio plays through default desktop audio device regardless of selection within the application. Unfortunately, I'm not sure after which update this started.

**Steps to Reproduce:**
Fresh install
Set audio output to anything

I saw the 4.0 ticket, but figured I'd open one anyway just in case.

**Comment by berryelectronics** [comment]
Please look at the closed issues first....

Quote from #1769:
' These are starting to annoy me now. This is fixed in master and will be out next release.

See these duplicates that you should have found before raising this issue:
#1761 #1755 #1722 #1714 #1707
'

**Comment by Dokupe** [comment]
Fair enough, but the default is set to display and search open issues. Maybe consider leaving something there so it's actually visible.

**Comment by berryelectronics** [comment]
Well would be a bit Counter productive to see the solved problems first instead of the open ones

**Comment by MarshallOfSound** [comment]
@Dokupe It doesn't make sense to leave fixed issues open???  Just change your search to search closed issues.  Even just clicking "closed" on the first page their are multiple duplicates for this issue 😢

**Comment by Dokupe** [comment]
And you never stopped to consider why people are constantly making dupes of the same issue, huh?
Sure, of course checking the closed issues would make sense normally. But the issue is fixed, yet not pushed live yet. Which means? That's right, no open ticket for an obviously still broken feature in the latest version, you wouldn't immediately assume it's already fixed.

I never said leave the issue itself open, just make note of it somewhere to prevent people creating multiple duplicates. But hey, I doubt this will be the last time it happens, so have fun with the next one then.

**Comment by MarshallOfSound** [comment]
@Dokupe I'm not going to have a debate about how to use GitHub.  Every single project I know, use or maintain follows the same procedure.

Issues Raised -> Fix Issue -> Close Issue -> Time Passes -> Release

If people don't check closed issues that's on them, and when I close as a duplicate I will inform them as such in the hopes that they will check next time.

>  just make note of it somewhere

I would make a note of fixed issues in the ISSUE_TEMPLATE file if I though it would help, but considering that one of the first lines in that file (that you have to read when making an issue) is:

> * I have checked that there are no issues with similar or the same content

And it appears you and other ignored that requirement I don't think it would help at all...

**Comment by Dokupe** [comment]
Technically there aren't any other open issues with the same content, so you're discounting that people checked at all. Neglected to checked closed issues, sure, but that doesn't mean your requirement was ignored. How about making that explicit then? I'd imagine it'll remind or inform people who don't use github as regularly as you do not to forget to check closed issues.

Or you can just get annoyed every time it happens and wonder why oh why everyone seems to ignore your requirements despite being so clearly established and universally understood.

┐(￣ー￣)┌

**Comment by MarshallOfSound** [comment]
As I said, I'm not going to have this debate.  It is commonplace on GitHub and other issue tracking systems to check the closed issues before raising a new one....
