### ISSUE TITLE
UI broken after latest Google update

### ISSUE THREAD

**Issue by FezVrasta** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1894]
I'm just reporting this to bring it to your attention.

![image](https://cloud.githubusercontent.com/assets/5382443/20264722/4c9b2ce6-aa6d-11e6-912e-196150cc4152.png)

![image](https://cloud.githubusercontent.com/assets/5382443/20264741/695b7598-aa6d-11e6-8061-2db0e944333a.png)

**Comment by MarshallOfSound** [comment]
/cc @chrismou @jacobwgillespie @GPMDP-Magical-Unicorn @jostrander 

Things broke yo

**Comment by chrismou** [comment]
Holy fragoles!

That's what I get for not restarting my player for a few days :scream:

**Comment by MarshallOfSound** [comment]
@chrismou Only just happened AFAIK I restarted my player not 2 hours ago and still had the old UI.

**Comment by chrismou** [comment]
FWIW, IMO the new front page is fuuugly

Who was that guy on here who worked for Google?  I need to get him to tell the gmusic team I'm not happy :joy:

**Comment by MarshallOfSound** [comment]
> FWIW, IMO the new front page is fuuugly

I agree, currently patching `gmusic-theme.js` now.  It looks like `gmusic.js` itself though is still working.

**Comment by MarshallOfSound** [comment]
It doesn't help that even without modifications their new UI is buggy and doesn't work correctly....

**Comment by FezVrasta** [comment]
I see some random white flashes by time in time

**Comment by MarshallOfSound** [comment]
@FezVrasta I'm getting those as well, appears to be on GPM's side of things as I get them without the theme enabled.  Strange white lines at the top of the screen.  Making progress on fixing the theming.

https://github.com/gmusic-utils/gmusic-theme.js/commit/584e13551dcb4a70e7432c5b6b41aa65f9f7dde1

Just checking the light theme now

**Comment by jostrander** [comment]
Hopefully they aren't tampering with it at the moment as well or we'll have to do this all over again soon.

**Comment by MarshallOfSound** [comment]
Also took the liberty in our theming library of killing the stupid amount of padding they added between blocks.  **148px** seemed a bit much

**Comment by MarshallOfSound** [comment]
`4.0.3` is being cooked up by the CI agents right now 👍

**Comment by chrismou** [comment]
Is there a way of forcing an update check on the linux client?  I ran into this the other day, where I ended up just downloading the new version manually and installing over the top

**Comment by MarshallOfSound** [comment]
@chrismou There isn't an auto-update on the linux client *still*

Not sure the `auto-update` part is technically possible and I've never had the effort to make a simple update check / notification thing 😢 

So yeah, for now, install over 👍 😆

**Comment by chrismou** [comment]
If I end up staying on Linux much longer, maybe I'll set up a Debian repository so we can install and update it with apt :joy: 

https://wiki.debian.org/SettingUpSignedAptRepositoryWithReprepro

**Comment by jostrander** [comment]
We actually have an apt repo somewhere in the abyss... @MarshallOfSound would know where at

**Comment by MarshallOfSound** [comment]
@chrismou 

https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/docs/Installation_On_Debian.md

**Comment by chrismou** [comment]
Oh cool, so there is a way of getting updates through - just not how I installed it :joy:

**Comment by MarshallOfSound** [comment]
👍

**Comment by chrismou** [comment]
Although saying that, it's stuck on 3.2.4

**Comment by chrismou** [comment]
I should probably stick this in another issue ticket, if it's actually an issue.  Sorry, polluting this closed ticket...

**Comment by MarshallOfSound** [comment]
@chrismou I just published `4.0.3` on that bintray repo.  It should be up there (might take a while for the CDN to update).  The `4.x` releases never hit it because my auto-upload thing only handled `3.x` 😆

**Comment by chrismou** [comment]
Interestingly though, the Debian package has already updated (https://dl.bintray.com/marshallofsound/deb/dists/debian/main/binary-amd64/Packages

Anyways, I've switched the sources file to use that and it looks to be pulling the latest update through. Sweeet.  :smile:

**Comment by MarshallOfSound** [comment]
👍

**Comment by FezVrasta** [comment]
I'm still having problems guys:

![image](https://cloud.githubusercontent.com/assets/5382443/20305192/9eeadb64-ab34-11e6-8092-b778b1a534da.png)


![image](https://cloud.githubusercontent.com/assets/5382443/20305195/a2b8c6d4-ab34-11e6-8134-7aa7b92770ec.png)
![image](https://cloud.githubusercontent.com/assets/5382443/20305198/a7b55a26-ab34-11e6-856e-95c9be3ec251.png)

**Comment by MarshallOfSound** [comment]
@FezVrasta See https://github.com/gmusic-utils/gmusic-theme.js/issues/60

The last 2 images I can see the issue and it has been fixed in that issue mentioned above.  I can't see what the issue is in the first image 👍

**Comment by FezVrasta** [comment]
In the first image, the navigation dots are white on a super light grey background and are almost invisible. They should probably be of the same color of the accent (in my case, dark gray)

**Comment by MarshallOfSound** [comment]
@FezVrasta How did you get a white background behind those dots?  (Like which page)

**Comment by FezVrasta** [comment]
It's the main page with the light theme.

![image](https://cloud.githubusercontent.com/assets/5382443/20306163/3bceb3a2-ab39-11e6-881f-4cf40e91481e.png)

**Comment by FezVrasta** [comment]
I see that, in some sections, the dots are correctly white, but probably they should change based on the context (I guess the native Google Music interface already addresses this problem)

![image](https://cloud.githubusercontent.com/assets/5382443/20306247/99ac68e8-ab39-11e6-89af-786988a6df58.png)

**Comment by FezVrasta** [comment]
This is the behaviour in the web interface:

![web-ui](https://cloud.githubusercontent.com/assets/5382443/20306317/f27b859e-ab39-11e6-9a10-1d218b344dc9.gif)

**Comment by MarshallOfSound** [comment]
@FezVrasta Yep I just adjusted the theme to only override the page indicator fill color on the dark theme.  (The CSS had ended up in the common file for some reason).  All the issues you mentioned are now fixed upstream 👍

**Comment by FezVrasta** [comment]
Great 😬

**Comment by deletescape** [comment]
![image](https://cloud.githubusercontent.com/assets/13785669/20481247/8167fb92-afe6-11e6-8365-64e260b78331.png)
If I leave GPMDP in the background and reopen it after sometime the background on the Home page sometimes changes back to white for some reason.

Didn't open a new issue because it looks similar to some other issue which has been discussed in here. If you want a new issue for this I can open one.

Win 7 Enterprise x64
I'm on the latest successfull CI build
