### ISSUE TITLE
Library tabs not styled correctly with dark theme

### ISSUE THREAD

**Issue by CorruptComputer** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2634]
**OS:** Windows 10

**Issue Descriptions:** 
![image](https://user-images.githubusercontent.com/5573038/28050744-256ab4c0-65c5-11e7-961d-1f2625f55a28.png)

**Steps to Reproduce:** Open the library tab in the hamburger menu.

**Comment by MarshallOfSound** [comment]
Fixed in `4.4.0` release will be out asap

**Comment by CorruptComputer** [comment]
@MarshallOfSound Any ETA on release of 4.4.0?

**Comment by kmroz0991** [comment]
+1

**Comment by jonahwh** [comment]
Still seeing issues with this on the right side in 4.4.0

![image](https://user-images.githubusercontent.com/794237/28533583-8517b4a8-7052-11e7-896e-f21cf196af53.png)

**Comment by neogohan324** [comment]
Also seeing this issue with shuffle on 4.4.0

Light theme:
![image](https://user-images.githubusercontent.com/30501522/28675768-6b7f3b84-72ae-11e7-92eb-0bc5bc2a1ac0.png)

Dark:
![image](https://user-images.githubusercontent.com/30501522/28675757-5c4a7156-72ae-11e7-8ece-3f6a595ae55d.png)


Issue persists even after an uninstall/reinstall of the application.
