### ISSUE TITLE
Scrobbles not being saved, still (v4.4.1)

### ISSUE THREAD

**Issue by miketotman-sd** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2740]
* I checked the existing issues, including the closed issues: #2658 and #2609 seemed related, but they are fixed (I'm running 4.4.1) and I still have this issue
* I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* I have double checked and can reproduce the issue: I've been having this issue for several days and multiple reboots. I've removed and re-added the Last.fm authorization a couple of times.

If appropriate please attach the DEBUG information zip file that you can generate by following the instructions in the FAQ  

**OS:**
Windows 10 Pro, Version 1703, OS Build 15063.540

**Issue Descriptions:**
Scrobbles show up on Last.fm with "Now Playing" but are not saved when the new song starts.

**Steps to Reproduce:**

1. Play song in GPMDP
1. Watch Last.fm profile

This happens with the player open, not minimized.

I run virtual desktops (Win 10 built-in) but in case it was related to the minimized issue, I stayed on the same screen as the player and this still happened.

The last songs successfully scrobbled were from a Google Play Music radio station, then I switched to playlists of my own music and then it stopped scrobbling.

[debug_info.zip](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/1272447/debug_info.zip)

**Comment by affinage** [comment]
I have the same issue.
v4.4.1 @ macOS Sierra 10.12.6.

**Comment by traumaturge** [comment]
it's seems to be specifically music that has been uploaded by the user

music that's played directly from google's own catalogue will play fine for me, but if i swap to anything i've had to upload, scrobbling does not work at all

**Comment by affinage** [comment]
yeah. seems that none of my uploaded tracks appeared on last.fm. but also not all tracks that I played from google store albums appeared on last.fm too. 

attaching new [debug_info 2.zip](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/1276843/debug_info.2.zip) with unscrobbled google's songs just in case.

**Comment by andreynts** [comment]
same issue
v 4.4.1 ubuntu 16.04 LTS (core  4.8.0-52-generic)

**Comment by pdubla** [comment]
Same issue on Mac Sierra 10.12.6. GDMP version 4.4.1.

It does seem to be a problem with uploaded tracks. Google's catalog scrobbles.

**Comment by jostrander** [comment]
```{"message":"LASTFM ERROR","stack":"Error: getaddrinfo ENOTFOUND ws.audioscrobbler.com```

It looks to me like its a DNS/network related issue hence why its so consistent between versions for you.

**Comment by miketotman-sd** [comment]
I get this issue from two different locations (work & home) which both have very permissive network setups. What should I be looking at? Is there some more detail in the logs I can use to figure out exactly what's failing? e.g. the specific URI being accessed when it fails

**Comment by jostrander** [comment]
Could be a firewall? Its trying to connect to ws.audioscrobbler.com and the connection is reset, usually indicative of something killing the connection.

**Comment by miketotman-sd** [comment]
I don't see any rules in my firewall specific to GPMDP, and if I go to that URL in Chrome I get a web page that says "Please visit http://www.last.fm/api", so it doesn't appear to block that location in general.

I never got a popup from the firewall when first installing GPMDP, so I assumed it didn't need any specific ports opened. Presumably it's using the standard web/HTTP ports.

**Comment by MarshallOfSound** [comment]
@miketotman-sd That error normally comes from firewalls / proxies / vpn's getting in the way.  For those issues please see #921 

For issues where some tracks scrobble and others don't, this has been fixed in master 👍 

Happy to continue debugging discussion here but closing out as #921 tracks these issues

**Comment by miketotman-sd** [comment]
But I'm not using a proxy, and from what I can see I don't have any firewall rules blocking this communication. And I can do last.fm scrobbling from this computer using other desktop apps like VLC.

**Comment by pdubla** [comment]
Since I noticed this issue, I've only been listening to tracks from the Google library (mostly radio stations). Today I pushed play on a station I was listening to yesterday (I had not closed the client since yesterday). The tracks from yesterday had scrobbled, but the tracks played today did not scrobble. After re-starting the client, it started scrobbling again.

**Comment by au5ton** [comment]
@pdubla restarting the client worked for me too, not sure why it stopped working.

**Comment by affinage** [comment]
seems that scrobbling for tracks from Google library stopped working each time when I left my Mac sleep overnight with GPMDP on background (I mean just close laptop for a night).

so I don't get how this is can be network-related issue.

**Comment by au5ton** [comment]
To clarify, restarting the app on Windows fixed scrobbling, still broken on my Mac.

**Comment by Angryhead** [comment]
Having this issue on both Windows 10 (at home) & Mac Sierra 10.12.6 (at work) GDMP version 4.4.1. No help from restarting player or restarting the computer. Tracks from my own library don't scrobble (but show up as Now Playing) while tracks from the Google library do scrobble.

**Comment by au5ton** [comment]
same situation as @Angryhead

**Comment by jupiterssj4** [comment]
Same issue as @Angryhead. Nothing has scrobbled since Oct 25 for me (it's Oct 30). I've listened to 6 albums since then. I'm logged in, authorized, it shows as Now Playing then doesn't show in recently listened to on Last.fm. Restarting PC, program doesn't help. No proxies. Windows 10 Pro x64 v1703

**Comment by pdubla** [comment]
I'm still having the issue that tracks don't scrobble when they're from my own library. Non-library tracks have been working for me, even when not restarting the client.

**Comment by KaeruCT** [comment]
I'm still having this issue and I think it has to do with this  lastfm-node issue

https://github.com/jammus/lastfm-node/issues/28

**Comment by MarshallOfSound** [comment]
> I'm still having this issue and I think it has to do with this lastfm-node issue

The fix for this hasn't been released yet, this issue doesn't occur on master

**Comment by ryanbr** [comment]
So it should fix this issue in 4.4.1? https://www.youtube.com/watch?v=CGL4QkpiOSk

**Comment by swdelaney2** [comment]
Also on 4.4.1 on Mac and experiencing the same issue.

**Comment by d1zzy** [comment]
Would appreciate an updated build that fixes this issue, haven't had last.fm scrobbles since Oct :(

**Comment by pdubla** [comment]
Please push this fix!

**Comment by affinage** [comment]
yep. can confirm. 
4.5.0 @ macos sierra 10.12.6 scrobbling my uploaded tracks works and also scrobbling of google's songs works after sleep

thanks!
