### ISSUE TITLE
What should happen to the windows application when there is no active internet connection!!

### ISSUE THREAD

**Issue by adityamadhu20** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2769]
**OS:**

**Issue Descriptions:**

**Steps to Reproduce:**

**Comment by jostrander** [comment]
Tagged as bug and enhancement because I know this is an issue, but kind I believe it was solved already at some point. Maybe an enhancement to get rid of the white screen of death?

**Comment by Alipoodle** [comment]
I've had GPM blocked on my work network (mainly due to an IT Error) but that left me on a black screen instead. The spinner seemed to spin for a while and vanish. As it's not happened in a while I cannot confirm that this is still the same!

**Comment by reduckted** [comment]
I have a similar situation. When I start my PC, my VPN starts up at about the same time as GPMDP. When my VPN starts, it stops all network traffic. Because GPMDP starts at about the same time, when it first loads, there is no network connection and I just end up with a blank white page. I have to close GPMDP and restart it once the VPN connects. The VPN still allows LAN traffic, so the "offline page" doesn't take effect.

I've created #3763 to address this.
