### ISSUE TITLE
Downloaded the new version of the app now i'm stuck on Youtube Music

### ISSUE THREAD

**Issue by ZephhyLeo** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3707]
Hey I downloaded the newest version of the app cause I was having loading problems and now I'm stuck on Youtube Music.

I uninstall and clear all of my files and I'm still stuck, even on installing older versions I still get the Youtube music page, the back button doesn't even work.

Been trying for hours trying to get it back the way it was but i'm stuck.

**Comment by JLIspace** [comment]
same..

**Comment by mortie** [comment]
I'm in the same situation; I just built GPMDP from the latest commit to master (3f36c34249ed5b768be52b6b228236f55bede63e, because I had the issues signing in mentioned in other issues). After logging in, I had a big red button in the top right which said something like "Try out YTM", I was curious and clicked it, now I'm stuck on a screen which says "Sorry, YouTube Music is not optimized for your browser" and suggests I download Chrome.

Man, Google sure is getting more and more aggressive about trying to force people to use Chrome, and only Chrome, for everything...

**Comment by mortie** [comment]
Clearing out all data related to GPMDP is a workaround which works for me, it logs me out, and when I log back in, I'm back to Google Play Music. The big red "SWITCH TO YTM (BETA)" button is still there though.

To clear your user data, delete GPMDP user data directory. That's `~/.config/Google Play Music Desktop Player` on Linux. According to random results on Google, the corresponding folder on macOS is `~/Library/Application Support/Google Play Music Desktop Player`, and `%APPDATA%/Google Play Music Desktop Player` on Windows.

Make sure to actually shut down GPMDP before deleting that folder. Since GPMDP prevents you from quitting it (binding the X button and right click -> Quit button to minimize), you might have to kill it using resource monitor or similar).

**Comment by jostrander** [comment]
The application has a tray icon that you can use to switch services. Right click on and it switch back to GPM. The button inside the page is a new feature, but obviously its not fail proof if the other service doesn't load for you.

**Comment by IndefiniteBen** [comment]
This is the same root issue mentioned in #3706 and #3688, originally mentioned in #3545 and with a solution mentioned in #3660.

**Comment by abion136** [comment]
@IndefiniteBen I'm not entirely sure this is the same root issue. It appears one issue has to do with signing into the service and the other with actually initializing the GUI. 

#3706 and #3660 relate to the GUI not initializing correctly and were fixed as per https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/3660#issuecomment-548558168. However, the issues logging into GPM and YTM are issues related to #3545 witch seems to be a User Agent issue.

I could very well be wrong, I'm still green in this arena, but those are my thoughts.

To anyone having these issues try checking out the latest CI builds:
- [Windows](https://ci.appveyor.com/project/MarshallOfSound/google-play-music-desktop-player-unofficial/build/artifacts)
- [Linux/Mac](https://circleci.com/gh/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-)

**Comment by HanSolo80** [comment]
@IndefiniteBen This is for sure a different issue. I am getting the same browser not compatible error using the latest working CI build 1.0.2827.
The issue mentioned in #3660 got resolved with that build, but the issue regarding the browser not compatible issue remains.

**Comment by jostrander** [comment]
While this is technically a different issue it's the result of an incorrect User Agent fix from #3545 . It's not windows related. It's still being tracked there.

**Comment by nzchicken** [comment]
For anyone else stuck on Youtube Music, you can just change one small setting instead of deleting the whole cache.
Open `~/Library/Application Support/Google Play Music Desktop Player/json_store/.settings.json` and change `service` to google-music. Restart GPMDP.
