### ISSUE TITLE
last.fm scrobbling not working in 1.9.0

### ISSUE THREAD

**Issue by eligrey** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#62]
I suspect it may be due to all of the special characters in my password. It looks like you're not url-encoding [your parameters](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/30bd635c8d336cefc4d4b48305431252edde7907/Google%20Play%20Music/LastFM.Intergration.cs#L111).

**Comment by MarshallOfSound** [comment]
I will try test this by changing my password to include special chars

**Comment by MarshallOfSound** [comment]
Issue confirmed, definitely URL encoding.  Thinking I should fix this ASAP and push out a `1.9.1` release

**Comment by MarshallOfSound** [comment]
@eligrey Update should be being pushed out now

**Comment by eligrey** [comment]
I can confirm that this fixed it for me.

**Comment by MarshallOfSound** [comment]
No problem, I hate having to tag something as a breaking bug.  Gotta get rid of it as quick as possible

**Comment by sorif** [comment]
I'm afraid this is still an issue for me with 1.9.1

Unable to login. I can only see the "enter username" field, and no matter what I type in there, I see a red "login failed". It doesn't even matter if I close and restart the application.

ps
sorry if I shouldn't have mentioned this here, it's the first time I'm posting anything on github :) keep up the great work on this, many many thanks!

**Comment by MarshallOfSound** [comment]
@sorif so you cant see the password field????

**Comment by sorif** [comment]
Exactly. This is what I'm seeing. I installed the 64-bit version, in case you need to know.
![googlemusicdesktoplastfmloginbug](https://cloud.githubusercontent.com/assets/8431264/11453797/d9199704-9621-11e5-949c-cd5bc91e544f.PNG)

**Comment by MarshallOfSound** [comment]
That looks like exactly what you should see.  Have you typed in your last.fm username and pasword into those two fields.  Once you have done that, hit enter and it should say "Logging in" followed by "log in success"

**Comment by sorif** [comment]
Oh, I just got it. I was typing my username in the password field. Whoops.

All is good now.

**Comment by MarshallOfSound** [comment]
@sorif :stuck_out_tongue_winking_eye: Interesting trick, but glad its working now :smile_cat:
